name: Testing workflow
run-name: Testing workflow
on:
  push:
  workflow_dispatch:

jobs:
  testing:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Run test class SimpleClassTest
        run: java -jar lib/junit-platform-console-standalone-1.10.2.jar --class-path bin --select-class SimpleClassTest

  report:
    needs: testing
    if: ${{ always() }}
    runs-on: ubuntu-latest

    steps:
      - name: Sucsess test
        if: ${{ needs.testing.result == 'success' }}
        uses: cbrgm/telegram-github-action@v1
        with:
          token: ${{ secrets.TELEGRAM_TOKEN }}
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          message: |
            *Testing workflow: SUCCESS*
            Repository: ${{ github.repository }}

      - name: Failure test
        if: ${{ needs.testing.result == 'failure' }}
        uses: cbrgm/telegram-github-action@v1
        with:
          token: ${{ secrets.TELEGRAM_TOKEN }}
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          message: |
            *Testing workflow: FAILURE*
            Repository: ${{ github.repository }}
            Reason: https://github.com/deeffoora/Testing/actions/workflows/auto.yml

